services:
  pgadmin:
    image: dpage/pgadmin4:8
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_PROXY_X_HEADERS=True
      - PGADMIN_CONFIG_ENABLE_PWD_COMPLEXITY_CHECK=False
    networks:
      - transcendence_network
      - monitoring_network

  grafana:
    image: grafana/grafana:10.4.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - prometheus_config:/etc/prometheus
      - ./prometheus/prometheus.yml:/tmp/prometheus.yml:ro
      - ./prometheus/init/init.sh:/bin/init.sh:ro
      - prometheus_data:/prometheus
    command: 
      - "/bin/init.sh"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring_network

volumes:
  pgadmin_data:
  prometheus_data:
  grafana_data:
  prometheus_config:

networks:
  transcendence_network:
    external: true
    name: 42_cursus_ft_transcendence_transcendence_network
  monitoring_network:
    driver: bridge