services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transcendence_network

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - transcendence_network

  web:
    build:
      context: ./django
    volumes:
      - ./django/src/static:/django/src/static
      - ./django/src/media:/django/src/media
      #      - static_data:/django/src/static
      # - media_data:/django/src/media
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - transcendence_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/monitoring-subdomains.conf:/etc/nginx/conf.d/monitoring.conf
      - ./django/src/static:/usr/share/nginx/html/static
      - ./django/src/media:/usr/share/nginx/html/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
      - pgadmin
      - grafana
      - prometheus
    restart: unless-stopped
    networks:
      - transcendence_network
      - monitoring_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email contact@pong.ovh
      --agree-tos
      --no-eff-email
      --noninteractive
      --expand
      -d pong.ovh
      -d pgadmin.pong.ovh
      -d grafana.pong.ovh
      -d prometheus.pong.ovh
    networks:
      - transcendence_network

volumes:
  postgres_data:
  redis_data:
  static_data:
  media_data:

networks:
  transcendence_network:
    driver: bridge
  monitoring_network: #J'ai rajouté cette ligne mais je sais pas pourquoi elle y était plus
    driver: bridge
