services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: ./django
    volumes:
      - ./django/src/static:/app/src/static  # Pour que Nginx accède aux fichiers statiques
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./django/src/static:/usr/share/nginx/html/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ton_email@example.com --agree-tos --no-eff-email -d pong.ovh

volumes:
  postgres_data:
  redis_data: