global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: ['pong.ovh']
        labels:
          group: 'django'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          group: 'database'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          group: 'cache'
        
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          group: 'proxy'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'containers'