global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['pong.ovh:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['pong.ovh:9090']