global:
  scrape_interval: 15s # Intervalle de récupération des métriques

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: ['web:8000'] # Cible votre service Django (à adapter si vous exposez un endpoint /metrics)