# Generated by Django 4.2 on 2025-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_remove_user_email_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
