# Generated by Django 4.2 on 2025-02-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0009_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
