# Generated by Django 4.2 on 2025-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='snake_high_score',
            field=models.IntegerField(default=0),
        ),
    ]
