# Generated by Django 4.2 on 2025-02-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/arcane_from_arcane.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
