# Generated by Django 4.2 on 2025-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_friends_customuser_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
