# Generated by Django 4.2 on 2025-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gameinvitation_delete_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinvitation',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='gameinvitation',
            name='accepted',
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='game_type',
            field=models.CharField(choices=[('match', 'Match'), ('tournament', 'Tournament')], max_length=20),
        ),
    ]
