# Generated by Django 4.2 on 2025-03-10 11:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_recipient_gameinvitation_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameinvitation',
            options={},
        ),
        migrations.RenameField(
            model_name='gameinvitation',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='gameinvitation',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gameinvitation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='expires_at',
            field=models.DateTimeField(default=users.models.get_expiration_time),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='game_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='match_type',
            field=models.CharField(choices=[('regular', 'Regular Match'), ('tournament', 'Tournament')], default='regular', max_length=15),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
