# Generated by Django 4.2 on 2025-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_gameinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
