# Generated by Django 4.2 on 2025-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_gameinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='connection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
